wandb_version: 1

name:
  desc: null
  value: CPL
task:
  desc: null
  value: Tacred
shot:
  desc: null
  value: 5-shot
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727197221
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      - 95
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      - 95
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.10.14
      5: 0.17.0
      6: 4.44.2
      8:
      - 5
      13: linux-x86_64
